[package]
name = "narg"
version = "1.1.0"
authors = ["Neffc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
rayon = "1.5.0"